#-*- coding:utf-8 -*-

#euler002.py
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
不超过4000000的序列值中所有偶数的和
'''

fi = [1,1]

tmp = sum(fi)
while tmp < 4000000:
	fi.append(tmp)
	tmp = fi[-2] + fi[-1]

sumone = reduce(lambda x,y : x+y, [i for i in fi if i % 2 == 0])
print sumone
# print fi[-1]
# print fi[-2] + fi[-1]

# 4613732
# [Finished in 0.1s]
